"""inital mirtaions

Revision ID: e95cdc60c253
Revises: 
Create Date: 2023-01-03 16:19:21.218669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95cdc60c253'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('khachhang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', sa.String(length=40), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('khachhang', schema=None) as batch_op:
        batch_op.drop_column('f_name')

    # ### end Alembic commands ###
